---
# tasks file for osp-facts
- name: Fetch Instance Info
  os_server_facts:
    cloud: "{{ cloud_provider_name }}"
    region_name: "{{ cloud_region_name }}"
  register: result

- name: Add host
  add_host:
    name: "{{ item.public_v4 }}"
    group: "{{ item.metadata.group }}"
  with_items: "{{result.ansible_facts.openstack_servers}}"
  
- name: Add host
  add_host:
    name: "{{ item.public_v4 }}"
    group: "{{ item.metadata.deployment_name }}"
  with_items: "{{result.ansible_facts.openstack_servers}}"
