- hosts: localhost
  become: yes
  gather_facts: false

  vars:
    cloud_provider_name: "ospcloud"
    ext_sub: "ext-subnet-1"
    int_sub: "int-subnet-1"


  roles:
    - role: osp-network
      network_object_type: "network"
      network_name: "ext-network-1"
      network_external: "true"
