- hosts: localhost
  become: yes
  gather_facts: false

  vars:
    cloud_provider_name: "ospcloud"

  roles:
    - role: osp-securitygroup
      osp_secugroup_name: "app_servers"
      osp_secugroup_descr: "ports_open"
      osp_secugrouprule_list:
        - { port: '8080', ip_prefix: '0.0.0.0/0' }
        - { port: '22', ip_prefix: '0.0.0.0/0' }
    - role: osp-securitygroup
      osp_secugroup_name: "frontend_servers"
      osp_secugroup_descr: "ports_open"
      osp_secugrouprule_list:
        - { port: '80', ip_prefix: '0.0.0.0/0' }
        - { port: '443', ip_prefix: '0.0.0.0/0' }
        - { port: '22', ip_prefix: '0.0.0.0/0' }
    - role: osp-securitygroup
      osp_secugroup_name: "db_servers"
      osp_secugroup_descr: "ports_open"
      osp_secugrouprule_list:
        - { port: '5432', ip_prefix: '20.20.20.0/24' }
        - { port: '22', ip_prefix: '0.0.0.0/0' }
