- hosts: localhost
  become: yes
  gather_facts: false

  vars:
    cloud_provider_name: "ospcloud"

  #roles:
  #   - osp-network
  #   - osp-keypair
  #   - osp-securitygroup

  tasks:
  ##Create Fronend Instance
  - name: Create frontend instance
    include_role:
      name: osp-instance
      vars_from: frontend.yaml

  ###Create App1 server
  - name: Create app1 instance
    include_role:
      name: osp-instance
      vars_from: app1.yaml

  ##Create App2 server
  - name: Create app2 instance
    include_role:
      name: osp-instances
      vars_from: app2.yaml

  ##Create DB server
  - name: Create db instance
    include_role:
      name: osp-instances
      vars_from: db.yaml

  ##Get OSP facts
  - name: Get OSP facts
    include_role:
      name: osp-facts
