---
- os_router:
    cloud: "{{ cloud_provider_name }}"
    state: "{{ router_state }}"
    name: "{{ router_name }}"
    network: "{{ network_name }}"
    external_fixed_ips:
      - subnet: "{{ ext_sub }}"
    interfaces:
      - "{{ int_sub }}"
